FROM node:18-alpine

# Crear directorio de la aplicación
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias con legacy peer deps
RUN npm install --legacy-peer-deps

# Copiar código de la aplicación
COPY . .

# Exponer puerto
EXPOSE 3000

# Comando para desarrollo
CMD ["npx", "react-scripts", "start"]
