name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest --maxfail=1

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run vitest in CI mode
        env:
          CI: 'true'
        run: npm run test -- --run

  security-scan:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit
      - name: Run pip-audit
        working-directory: backend
        run: pip-audit -r requirements.txt
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
      - name: Run npm audit
        working-directory: frontend
        run: npm audit --audit-level=high

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-scan]
    steps:
      - name: Deployment placeholder
        run: |
          echo "Todos los chequeos superados. Despliegue automatizado pendiente de integración."
